# Упражнения по NumPy

Давайте проверим Ваши знания NumPy. Мы начнём с достаточно простых задач, и плавно перейдём к более сложным.

<div class="alert alert-danger" style="margin: 10px"><strong>ВАЖНОЕ ЗАМЕЧАНИЕ!</strong> Пожалуйста не запускайте ячейки, которые располагаются <br> непосредственно над ожидаемым результатом, иначе Вы удалите этот ожидаемый результат!</div>

#### 1. Импортируйте NumPy as np

In [1]:
import numpy as np

#### 2. Создайте массив из 10 нулей

In [2]:
# Напишите Ваше решение в этой ячейке
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Создайте массив из 10 единиц

In [3]:
# Напишите Ваше решение в этой ячейке
array_1 = np.ones(10)
print(array_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Создайте массив из 10 пятёрок

In [4]:
# Напишите Ваше решение в этой ячейке
array_5 = np.full(10, 5)
print(array_5)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Создайте массив целых чисел от 10 до 50 включительно

In [5]:
# Напишите Ваше решение в этой ячейке
arr_10_50 = np.arange(10, 51)
print(arr_10_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Создайте массив всех чётных чисел от 10 до 50 включительно

In [6]:
# Напишите Ваше решение в этой ячейке
arr_10_50_2 = np.arange(10, 51, 2)
print(arr_10_50_2)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Создайте матрицу 3x3 со значениями от 0 до 8 включительно

In [7]:
# Напишите Ваше решение в этой ячейке
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. Создайте единичную матрицу размером 3x3

In [9]:
# Напишите Ваше решение в этой ячейке
matrix_1 = np.eye(3)
print(matrix_1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. С помощью NumPy сгенерируйте случайное число в диапазоне от 0 до 1<br><br>&emsp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [10]:
# Напишите Ваше решение в этой ячейке
random_number = np.random.rand()
print(random_number)

0.2546724285482863


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.65248055])

#### 10. С помощью NumPy сгенерируйте массив из 25 случайных чисел, выбранных из стандартного нормального распределения<br><br>&emsp;&ensp;Замечание: Ваш результат может отличаться от того, что указано в качестве примера ниже.

In [11]:
# Напишите Ваше решение в этой ячейке
random_numbers_25 = np.random.randn(25)
print(random_numbers_25)

[ 1.04717496  0.01391833 -1.36840786  0.08456757 -0.03478256 -0.26256271
  0.04047701  0.09007912 -2.03398061  0.24699349 -0.84773235  1.15367519
 -0.04425261 -0.24073357 -0.04861553 -1.29096285  0.8411709  -0.17574472
 -2.24488067  1.99205976  0.30909304 -0.04224437 -0.33944821  0.59153956
  1.3043136 ]


In [12]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


#### 11. Создайте указанную ниже матрицу:

In [18]:
# Напишите Ваше решение в этой ячейке
matrix_100 = np.arange(0.01,1.01,0.01).reshape(10, 10)
print(matrix_100)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### 12. Создайте массив из 20 равноудалённых друг от друга точек между 0 и 1:

In [19]:
# Напишите Ваше решение в этой ячейке
array_20 = np.linspace(0, 1, 20)
print(array_20)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Индексация Numpy

Здесь Вы будете работать с некоторой матрицей - чтобы создать её, запустите следующую ячейку! После этого мы попросим Вас воспроизвести несколько результатов работы с этой матрицей:

In [20]:
# ЗАПУСТИТЕ ЭТУ ЯЧЕЙКУ - ЭТО СОЗДАНИЕ МАТРИЦЫ ДЛЯ СЛЕДУЮЩИХ ЗАДАНИЙ
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу (подсказка - используйте индексацию).

In [28]:
# Напишите Ваше решение в этой ячейке
print(mat[2::,1::])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [29]:
# Напишите Ваше решение в этой ячейке
print(mat[3,-1])

20


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


20

#### 15. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [32]:
# Напишите Ваше решение в этой ячейке
print(mat[:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[ 2],
       [ 7],
       [12]])

#### 16. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [33]:
# Напишите Ваше решение в этой ячейке
print(mat[4])

[21 22 23 24 25]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([21, 22, 23, 24, 25])

#### 17. Напишите код, который на основе матрицы mat выведет указанную ниже матрицу.

In [34]:
# Напишите Ваше решение в этой ячейке
print(mat[3::])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Операции в NumPy

#### 18. Найдите сумму всех чисел в матрице mat

In [35]:
# Напишите Ваше решение в этой ячейке
print(np.sum(mat))

325


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


325

#### 19. Найдите среднеквадратичное отклонение значений в матрице mat

In [36]:
# Напишите Ваше решение в этой ячейке
print(np.std(mat))

7.211102550927978


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


7.211102550927978

#### 20. Найдите сумму каждой из колонок в матрице mat

In [37]:
# Напишите Ваше решение в этой ячейке
print(np.sum(mat, axis=0))

[55 60 65 70 75]


In [ ]:
# НЕ ПИШИТЕ В ЭТОЙ ЯЧЕЙКЕ


array([55, 60, 65, 70, 75])

## Бонусный вопрос

Мы много работали со случайными данными в numpy, но есть ли способ каждый раз получать одни и те же "случайные" результаты? [Для подсказки нажмите здесь](https://www.google.com/search?q=numpy+random+seed&rlz=1C1CHBF_enUS747US747&oq=numpy+random+seed&aqs=chrome..69i57j69i60j0l4.2087j0j7&sourceid=chrome&ie=UTF-8)

In [38]:
# Напишите Ваше решение в этой ячейке
np.random.seed(1)
random_numbers = np.random.rand(5)
print(random_numbers)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01]


# Отличная работа!